# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Single trait logistic curve fit
#'
#' @param par  numeric of curve par
#' @param Times numeric of times
#'
#' @return vector of logistic curve number
#'
#' @export
hfun_g_t <- function(par, Times) {
    .Call(`_hfunmap_hfun_g_t`, par, Times)
}

#' Multi-trait logistic curve fit
#' @param par numeric of curve par
#' @param Times numeric of times
#'
#' @return  matrix dim = 1*length_n.trait*length_n.times
#'
#' @export
hfun_get_mu <- function(par, Times) {
    .Call(`_hfunmap_hfun_get_mu`, par, Times)
}

#' Multi-trait SAD1 inv & det
#' @param par numeric of covariance matrix par
#' @param Times numeric of times
#' @param ranks int, number of traits
#' @return  list $sigma_1=sigma_1;$det=det_sigma_1
#'
#' @export
hfun_get_invsigma <- function(par, Times, ranks) {
    .Call(`_hfunmap_hfun_get_invsigma`, par, Times, ranks)
}

#' H0 calculate mle
#' @param par numeric of mle par
#' @param N_phe input phenotype matrix
#' @param pheT numeric of times
#' @param ranks int, number of traits
#' @return  number of mle value
#'
#' @export
hfun_H0_mle <- function(par, N_phe, pheT, ranks) {
    .Call(`_hfunmap_hfun_H0_mle`, par, N_phe, pheT, ranks)
}

#' H1 calculate mle
#' @param par numeric of mle par
#' @param pheno list of pheno
#' @param Times numeric of times
#' @param ranks int, number of traits
#' @param ng int, number of geno type
#' @return  number of mle value
#'
#' @export
hfun_H1_mle <- function(par, pheno, Times, ranks, ng) {
    .Call(`_hfunmap_hfun_H1_mle`, par, pheno, Times, ranks, ng)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_hfunmap_RcppExport_registerCCallable', PACKAGE = 'hfunmap')
})
